########################################################################################
# MAIN HYPRLAND CONFIG FOR DEBIAN
########################################################################################

# Split config files
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/exec.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/windowrules.conf

# Input settings
input {
    kb_layout = us,nl          # Schakelen tussen US en NL layout
    kb_variant = ,             # Eventuele varianten
    follow_mouse = 1
    
    touchpad {
        natural_scroll = true  # "Apple-style" scrollen
        tap-to-click = true
    }

    sensitivity = 0            # -1.0 - 1.0, 0 betekent geen aanpassing
}

# General settings
general {
    gaps_in = 5                # Ruimte tussen schermen
    gaps_out = 10              # Ruimte tussen schermrand en windows
    border_size = 2
    
    # Mooie gradient border
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle           # De standaard "bswm-stijl" tiling
}

# Decoration
decoration {
    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

}

# Animations
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Dwindle options
dwindle {
    pseudotile = true 
    preserve_split = true 
}

# Misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 0
}

# Disable hardware cursor
cursor {
    no_hardware_cursors = true
}

# XWayland options
xwayland {
    force_zero_scaling = true
}
