# Polkit
exec-once = /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1

# Waybar and notifications
exec-once = waybar
exec-once = dunst

# Hyprpaper and Hypridle
exec-once = hyprpaper
exec-once = hypridle

# Cliphist
exec-once = wl-paste --type text --watch cliphist storeexec-once waybar
