# Polkit
exec-once = /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1

# Waybar and notifications
exec-once = waybar
exec-once = dunst

# Hyprpaper and Hypridle
exec-once = hyprpaper
exec-once = hypridle

# Cliphist
exec-once = wl-paste --type text --watch cliphist storeexec-once waybar

# Set dark mode
exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps
