# Polkit
exec-once = /usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1

# De Bar & Notificaties
exec-once = waybar
exec-once = dunst

# Hyprpaper
exec-once = hyprpaper

# Clipboard onthouden
exec-once = wl-paste --type text --watch cliphist storeexec-once waybar
